# Generated by Django 2.1.3 on 2018-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Django'), (3, 'PyCharm')], default=2),
            preserve_default=False,
        ),
    ]
