# Generated by Django 2.1.3 on 2018-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Django'), (3, 'PyCharm')])),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
